### ISSUE TITLE
Replace rm -rf with rimraf in clean script for cross env compatibility ?

### ISSUE THREAD

**Issue by marcfilleul** [brandonpittman/tailwindy#1]
Hi,

I've just cloned your starter and run into some issues.

As I'm a Windows user, rm -rf is an unknown command.
After some research I've found [this GitHub issue](https://github.com/oclif/oclif/pull/123) and tried the solution with success.

So here is a quick fix to have a cross platform working clean script:

- add rimraf in the devDependencies
- in package.json > clean script: replace rm -rf by rimraf

**Comment by brandonpittman** [comment]
done
